<?php

/**
 * @file
 * Install, update and uninstall functions for the utexas_smtp_helper module.
 */

/**
 * Implements hook_install().
 */
function utexas_smtp_helper_install() {
  $smtp_config = \Drupal::configFactory()->getEditable('smtp.settings');
  $smtp_config->set('smtp_username', '');
  $smtp_config->set('smtp_password', '');
  $smtp_config->set('smtp_on', TRUE);
  $smtp_config->set('smtp_autotls', TRUE);
  $smtp_config->set('smtp_host', '');
  $smtp_config->set('smtp_port', '');
  $smtp_config->set('smtp_protocol', '');
  $smtp_config->save();
}

/**
 * Implements hook_uninstall().
 */
function utexas_smtp_helper_uninstall() {
  $smtp_config = \Drupal::configFactory()->getEditable('smtp.settings');
  $smtp_config->set('smtp_on', FALSE);
  $smtp_config->set('smtp_autotls', FALSE);
  $smtp_config->save();
}
