<?php

/**
 * @file
 * Install, update and uninstall functions for the utexas_smtp_helper module.
 */

/**
 * Implements hook_install().
 */
function utexas_smtp_helper_install() {
  if (!function_exists('pantheon_get_secret')) {
    \Drupal::logger('utexas_smtp_helper')->error("Can't enable UTexas SMTP helper: Pantheon secrets function not available.");
    return;
  }
  \Drupal::state()->set('utexas_smtp', 1);
  $smtp_config = \Drupal::configFactory()->getEditable('smtp.settings');
  $smtp_config->set('smtp_username', '');
  $smtp_config->set('smtp_password', '');
  $smtp_config->set('smtp_on', '');
  $smtp_config->set('smtp_autotls', '');
  $smtp_config->set('smtp_host', '');
  $smtp_config->set('smtp_port', '');
  $smtp_config->set('smtp_protocol', '');
  $smtp_config->save();
}

/**
 * Implements hook_uninstall().
 */
function utexas_smtp_helper_uninstall() {
  \Drupal::state()->set('utexas_smtp', 0);
}
